service: lambda-async
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048 # optional, in MB, default is 1024
  timeout: 60 # optional, in seconds, default is 6
  stage: production
  region: us-west-2
  profile: eb-cli-async # https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

custom:
  dotenv:
    include: # review env vars
      - NODE_ENV
      - MONGO_URL_TEST
      - MONGO_URL
      - MONGO_URL2
      - PRODUCTION_URL_APP
      - PRODUCTION_URL_APP2
      - FROM_EMAIL_ADDRESS
      - AWS_REGION
      - AWS_ACCESSKEYID
      - AWS_SECRETACCESSKEY

functions:
  checkCardExpiration:
    handler: handler.checkCardExpiration
    events:
      - schedule: rate(7 days)